title: Md Maruf Billah
author: Md Maruf Billah
email: marufbillah03033@gmail.com
description: "Lead Software Engineer | Full-stack TypeScript (React, Next.js, Node.js, NestJS) | AWS & Azure"

github_username: maruf1020

show_excerpts: true

theme: jekyll-theme-cayman
